apiVersion: v1
kind: Service
metadata:
  name: node-web-app
  labels:
    run: node-web-app
spec:
  type: NodePort
  ports:
  - nodePort: 30000
    port: 8080
    targetPort: 8000
    protocol: TCP
  selector:
    app: node-web-app
  type: LoadBalancer
  externalIPs:
  - 3.37.204.255
