#Build Stage Start
FROM ubuntu:latest

#RUN Command
RUN echo Hello~ Its shell type command.
RUN ["echo", "Its shell type command."]
RUN ["/bin/bash","-c","echo 'Hello~ Its /bin/bash execution in shell type command.'"]


